### PR TITLE
Catppuccin Macchiato Flavor

### PR DESCRIPTION
**Pull request by beanOCE**
### catppuccin macchiato lavender

based on the macchiato palette of [catppuccin](https://catppuccin.com/palette) with lavender accents. Changed the corner text to differentiate between mocha and macchiato flavors, though I haven't done this for mocha as I don't know if it's a change worth making.

Screenshot 2024-09-09 170628

### CODE REVIEW

**Comment by refact0r** [comment]
can you update the colors for pink, green, yellow, etc. as well? those are still used even if they're not the primary accents.

**Comment by beanOCE** [comment]
Can do! For `--pink-1` and `--pink-2`, did you want me to update those as well? I just can't find the darker shades in the palette.

**Comment by refact0r** [comment]
just make your own then. you can convert to oklch and darken by roughly 10 lightness.

**Comment by beanOCE** [comment]
All updated and should be good to go :D

**Comment by refact0r** [comment]
thanks. is it ok if i add your name to the author list for this one? (bean or beanoce?)

**Comment by beanOCE** [comment]
Thanks! Just bean will be ok :D

**Pull request merged**
