### PR TITLE
Add gruvbox material theme

### PR DESCRIPTION
**Pull request by Sophed**

### CODE REVIEW

**Comment by refact0r** [comment]
thanks for the pr!

i noticed the font in the screenshot isn't DM Mono, did you want to include it in the theme?

**Comment by Sophed** [comment]
Oh my bad, I personally use Iosevka on my setup and forgot to change back to DM Mono for the screenshot. Would you prefer I add it in the theme or change the screenshot?

**Comment by refact0r** [comment]
up to you.

**Comment by refact0r** [comment]
is there a import link for the font you can add? i realized it's probably not good if people download the file and it looks like Times New Roman. 

if there isn't a good import link, maybe its just best to change it back to DM Mono and add different screenshot instead lol. sorry about that.

**Comment by Sophed** [comment]
Should be all good now, I couldn't find any good web imports for Iosevka :(

**Comment by refact0r** [comment]
great, thanks :)

**Pull request merged**
